### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by cabban** [ewwink/kodi-addon-subtitle-background#2]
Please make for opensubtitles also😀love it

**Comment by ewwink** [comment]
it simple task:
- go to `service.subtitles.opensubtitles_by_opensubtitles` directory
- download https://raw.githubusercontent.com/ewwink/python-srt2ass/master/srt2ass.py
- save it to `service.subtitles.opensubtitles_by_opensubtitles\resources\lib\srt2ass.py`
- edit line 214 of `service.subtitles.opensubtitles_by_opensubtitles\service.py`
- replace
```
for sub in subs:
    listitem = xbmcgui.ListItem(label=sub)
```
- with 
```
from resources.lib.srt2ass import srt2ass
for sub in subs:
    sub = srt2ass(sub) # convert .srt to .ass
    listitem = xbmcgui.ListItem(label=sub)
```

if you want to create multiple opensubtitles service/addon, copy and rename the directory and edit `addon.xml` `id` for example

`<addon id="service.subtitles.opensubtitles_by_cabban"`

**Comment by Jassemm** [comment]
it doesn't work with koodi 17 krypton... please fix it

**Comment by cabban** [comment]
@Jassemm  hahah, strange it works perfectly here _= )

**Comment by Jassemm** [comment]
@cabban Could you send me service file u have made.. in the log it tells me something wrong with service like not supported or something .. I really would appreciate if u provide it for me. Thanks
